# Generated by Django 4.0.6 on 2022-10-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceclient',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='cpf',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='indemnity',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='machine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='rg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceclient',
            name='total',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
