# Generated by Django 4.0.6 on 2022-11-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insuranceclient_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclient',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
