# Generated by Django 4.0.6 on 2022-10-03 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('value', models.FloatField()),
                ('type', models.CharField(max_length=255)),
            ],
        ),
    ]
