# Generated by Django 4.0.6 on 2022-08-03 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('birth_date', models.DateField(null=True)),
                ('rg', models.CharField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('house_number', models.IntegerField(null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('complement', models.CharField(max_length=255, null=True)),
                ('machine', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('photo', models.ImageField(null=True, upload_to='media')),
                ('instagram', models.CharField(max_length=255, null=True)),
                ('installments_value', models.FloatField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('last_payment', models.DateField(default=django.utils.timezone.now, null=True)),
                ('payment_status', models.IntegerField(default=3)),
                ('obs', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('installments_value',),
            },
        ),
    ]
