# Generated by Django 4.0.6 on 2022-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_serviceclient_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceclient',
            name='cpf',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serviceclient',
            name='rg',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
