# Generated by Django 4.0.6 on 2022-07-13 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controller", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Controller",
        ),
    ]
