# Generated by Django 4.0.6 on 2022-08-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('birth_date', models.DateField(null=True)),
                ('rg', models.CharField(max_length=255, unique=True)),
                ('cpf', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('house_number', models.IntegerField(null=True)),
                ('district', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('complement', models.CharField(max_length=255, null=True)),
                ('photo', models.ImageField(null=True, upload_to='media')),
                ('machine', models.CharField(max_length=255)),
                ('installments_value', models.FloatField(max_length=255)),
                ('total', models.FloatField(max_length=255)),
                ('payment', models.CharField(max_length=255)),
                ('obs', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ('machine',),
            },
        ),
    ]
