# Generated by Django 4.0.6 on 2022-10-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleclient_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleclient',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='cpf',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='installments_value',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='machine',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='payment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='saleclient',
            name='rg',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
