# Generated by Django 4.0.6 on 2022-11-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_saleclient_address_alter_saleclient_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleclient',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
